services:
  # Web Service - Next.js Application
  - type: web
    name: evolvoai
    env: node
    region: singapore
    plan: starter
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
      - key: TELEGRAM_ADMIN_ID
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        fromService:
          type: web
          name: evolvoai
          property: host
      - key: NEXT_PUBLIC_APP_URL
        fromService:
          type: web
          name: evolvoai
          property: host
      - key: CRON_SECRET
        generateValue: true
    healthCheckPath: /api/health

  # Background Worker (optional - for Telegram bot)
  - type: worker
    name: evolvoai-bot
    env: node
    region: singapore
    plan: starter
    buildCommand: npm install && npx prisma generate
    startCommand: npm run bot:start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: DATABASE_URL
        fromService:
          type: web
          name: evolvoai
          envVarKey: DATABASE_URL
      - key: TELEGRAM_BOT_TOKEN
        fromService:
          type: web
          name: evolvoai
          envVarKey: TELEGRAM_BOT_TOKEN
      - key: TELEGRAM_CHANNEL_ID
        fromService:
          type: web
          name: evolvoai
          envVarKey: TELEGRAM_CHANNEL_ID
      - key: TELEGRAM_ADMIN_ID
        fromService:
          type: web
          name: evolvoai
          envVarKey: TELEGRAM_ADMIN_ID

# Database (optional - use external PostgreSQL)
databases:
  - name: evolvoai-db
    databaseName: evolvoai
    user: evolvoai
    region: singapore
    plan: starter
